import UIKit

// MARK: TUGAS BASIC SWIFT

// 1. BUAT DEFINISI VARIABEL BERTIPE STRING, FOUBLE, FLOAT, INTEGER, BOOLEAN KEMUDIAN PRINT DATANYA

// 2. BUAT PROGRAM CONDITIONAL MENGGUNAKAN IF ELSE -> MENGANDUNG OPERATOR LOGIKA DAN PERBANDINGN >= , <= , \\, &&

// 3. BUAT ARRAY BARU DARI DEFAULT KEMUDIAN MANIPULASI DATANYA
// MENGGUNAKAN APPEND, REMORE, FILTER, COUNT DLL

//
