//: [Previous](@previous)

import Foundation

// MARK: TUGAS BASIC SWIFT

// 1. BUAT DEFINISI BARIABEL BERTIPE STRING, INTEGER, FLOAT, DOUBLE, BOOLEAN

// 2. BUAT PROGREAM CONSITIONAL MENGGUNAKAN IF ELSE -> MENGANDUNG OPERATOR LOGIKA DAN PERBANDINGAN >= <=, && ||

// 3. BUATLAH ARRAY BARU DENGAN DEFAULT VALUE KEMUDIAN MANIPULASI DATANYA
// -> MENGGUNAKAN APPEND REMOVE FILTER COUNT DLL

// 4. BUATLAH DICTIONARY DENGAN DEFAULT VALUE KEMUDIAN MANIPULASI DATANYA
// > MENGGUNAKAN APPEND REMOVE FILTER COUNT DLL

// 5. BUATLAH FUNGSI DENGAN PARAMETER YANG MENGHASILKAN RETURN
// FUNGSI ADA UNSUR SWITCH CASE ATAU IF ELSE

// 6. BUATLAH FUNGSI YANG MEMILIKI PARAMETER DENGAN ENUM DAN MEMILIKI RETURN

// 7. BUATLAH VARIABEL DENGAN COMPUTED PROPERTY

// 8. BAUTLAH VARIABEL DENGAN GETTER SETTER

// 9. BUATLAH FUNGSI YANG ADA LOOPINGNYA DAN PARAMETERNYA DARI ARRAY

// 10. BUATLAH SEBUAH CLASS YANG MEMILIKI INIT, PROPERTI DAN METHODE
